module.exports = {
  AdaptiveCard: 'card',
  TextBlock: 'text',
  ImageSet: 'images',
  Image: 'image',
  Container: 'container',
  ColumnSet: 'columns',
  Column: 'column',
  FactSet: 'facts',
  Fact: 'fact',
  Actions: 'actions',
  CardElements: 'body',

  Action: 'action',
  'Action.OpenUrl': 'action',
  'Action.Submit': 'action',
  'Action.ShowCard': 'action',

  Input: 'input',
  'Input.Text': 'input',
  'Input.Number': 'input',
  'Input.Date': 'input',
  'Input.Time': 'input',
  'Input.Toggle': 'input',
  'Input.ChoiceSet': 'choices',
  'Input.Choice': 'choice',
};
